#!/usr/bin/perl6

=begin pod

=head1 NAME

10-dns_grammar

=head1 SYNOPSIS


tests for dns_grammar


=head1 DESCRIPTION

tests an application that reads in a configuration file, as provided.  It then does a bunch of
different things.  I'll probably add more here eventually


=head1 GENERATED BY

Some guy with a keyboard

=head1 AUTHOR

Colin Wass

=head1 LICENSE


Copyright (c) 2018 - 2021, Colin Wass, The IMT
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the
following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or
promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
DAMAGE.

=head1 THOUGHTS

So, I think it better to test results rather than methods.  Therefore, I really don't care how the grammar gives me 
the correct result, only that it does.  In other words, the tests are written as though against an API.

=end pod



use lib '../lib';
use dns_grammar;
use Test;

use-ok('dns_grammar', 'Can load "DNS Grammar" ok');

my $TestGrammar;

#we're testing a grammar here, so this should all be simple inject strings confirm output.
#Note I expect some of these strings to eventually get straight up mean.

# Confirm Grammars work as expected:
say "Starting:  ";
$TestGrammar = DNS_grammar.parse(qw/autodiscover		IN	CNAME		autodiscover.outlook.com./, actions => DNS_captures);
is $TestGrammar.made<line><type>, "CNAME", "2: Checking I can spot the CNAME";
is $TestGrammar.made<line><value>, "autodiscover", "3: Checking I parse it correctly";
is $TestGrammar.made<line><additional>, "autodiscover.outlook.com.", "4: Checking the CNAME actually points at something";

$TestGrammar = DNS_grammar.parse(qw/csulabvpn		IN	A		207.35.78.202/, actions => DNS_captures);
is $TestGrammar.made<line><type>, "A", "5: Checking I can spot an A record";
is $TestGrammar.made<line><value>, "csulabvpn", "6: Confirming I get a hostname";
is $TestGrammar.made<line><additional>, "207.35.78.202", "7: Confirming I get the address";

# See note in parser in v6addr token, this is a pretty easy example, should probably be pathological

$TestGrammar = DNS_grammar.parse(qw/netlab2			IN	AAAA		2001:470:1D:95D::254/, actions => DNS_captures);
is $TestGrammar.made<line><type>, "AAAA", "8: Checking I can spot an AAAA record";
is $TestGrammar.made<line><value>, "netlab2", "9: Confirming I get a hostname";
is $TestGrammar.made<line><additional>, "2001:470:1D:95D::254", "10: Confirming I get the address";

$TestGrammar = DNS_grammar.parse(qw/woodroffe-2			IN	A		10.254.10.10/, actions => DNS_captures);
is $TestGrammar.made<line><type>, "A", "11: Checking I can spot an A record";
is $TestGrammar.made<line><value>, "woodroffe-2", "12: Confirming I get a hostname";
is $TestGrammar.made<line><additional>, "10.254.10.10", "13: Confirming I get the address";


done-testing; 
