#!/usr/bin/perl6

=begin pod

=head1 NAME

10-dns_grammar

=head1 SYNOPSIS


tests for dns_grammar


=head1 DESCRIPTION

tests an application that reads in a configuration file, as provided.  It then does a bunch of
different things.  I'll probably add more here eventually


=head1 GENERATED BY

Some guy with a keyboard

=head1 AUTHOR

Colin Wass

=head1 LICENSE


Copyright (c) 2018 - 2021, Colin Wass, The IMT
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the
following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or
promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
DAMAGE.

=head1 THOUGHTS

So, I think it better to test results rather than methods.  Therefore, I really don't care how the grammar gives me 
the correct result, only that it does.  In other words, the tests are written as though against an API.

=end pod



use lib '../lib';
use dns_data;
use Test;

use-ok('dns_data', 'Can load "DNS Data" ok');

my $TestData = DNS_data.new();

# Confirm API is complete

can-ok $TestData, "ingest", "1: Framework understands ingest";
can-ok $TestData, "A", "2: Framework understands a records";
can-ok $TestData, "AAAA", "3: Framework understands aaaa records";
can-ok $TestData, "CNAME", "4: Framework understands cname records";
can-ok $TestData, "get_record", "5: Framework will allow retrieving a record";
can-ok $TestData, "get_cname", "6: Framework will allow retrieving a cname record";
can-ok $TestData, "csv_out", "7: Framework will allow dumping to file";

my %TestBlock = %("type" => "A",
				"value" => "csulabvpn",
				"additional" => "207.35.78.202");
$TestData.ingest(%TestBlock);
is $TestData.get_record("csulabvpn"), "207.35.78.202", "8: Can set and retrieve an a record";
%TestBlock = %("type" => "AAAA",
				"value" => "netlab2",
				"additional" => "2001:470:1D:95D::254");
$TestData.ingest(%TestBlock);
is $TestData.get_record("netlab2"), "2001:470:1D:95D::254", "9: Can set and retrieve an aaaa record";
%TestBlock = %("type" => "CNAME",
				"value" => "autodiscover",
				"additional" => "autodiscover.outlook.com.");
$TestData.ingest(%TestBlock);
is $TestData.get_cname("autodiscover"), "autodiscover.outlook.com.", "10: Can set and retrieve a cname record";


done-testing; 

 
